---
# Install and configure l2chroot.
- name: See if l2chroot is already installed.
  stat:
    path: "{{ ssh_chroot_l2chroot_path }}"
  register: l2chroot_stat

- name: Ensure l2chroot is available.
  get_url:
    url: "{{ ssh_chroot_l2chroot_url }}"
    dest: "{{ ssh_chroot_l2chroot_path }}"
    mode: 0755
  when: not l2chroot_stat.stat.exists

- name: Ensure l2chroot uses the configured jail path.
  lineinfile:
    path: "{{ ssh_chroot_l2chroot_path }}"
    regexp: "^BASE=.+"
    line: 'BASE="{{ ssh_chroot_jail_path }}"'

# Add libs required by ssh_chroot_bins using l2chroot.
- name: Add binary libs using l2chroot.
  command: "l2chroot {{ item.bin | default(item) }}"
  changed_when: False
  when: item.l2chroot is not defined or item.l2chroot
  with_items: "{{ ssh_chroot_bins }}"
