---
- name: restart ssh daemon
  service:
    name: "{{ ssh_daemon }}"
    state: restarted

- name: copy ssh-chroot-jail extra items
  copy:
    src: "{{ item }}"
    dest: "{{ ssh_chroot_jail_path }}{{ item }}"
    remote_src: true
  with_items: "{{ ssh_chroot_copy_extra_items }}"

- name: add binary libs via l2chroot
  command: "l2chroot {{ item.bin | default(item) }}"
  when: item.l2chroot is not defined or item.l2chroot
  with_items: "{{ ssh_chroot_bins }}"

- name: copy extra libraries for whoami
  command: "cp {{ lib64_path }}/libns* /var/jail/{{ lib64_path }}/"
  when: "'/usr/bin/whoami' in ssh_chroot_bins"
